In [1]:
!pip install datasets

Collecting datasets
  Using cached datasets-3.2.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: filelock in c:\users\aviral verma\anaconda3\lib\site-packages (from datasets) (3.13.1)
Requirement already satisfied: numpy>=1.17 in c:\users\aviral verma\anaconda3\lib\site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in c:\users\aviral verma\anaconda3\lib\site-packages (from datasets) (16.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\users\aviral verma\anaconda3\lib\site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in c:\users\aviral verma\anaconda3\lib\site-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\aviral verma\anaconda3\lib\site-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\aviral verma\anaconda3\lib\site-packages (from datasets) (4.66.5)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in c:\users\aviral verma\anaconda3\lib\site-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets) (2024.6.1)
Requirement already satisfied: aiohttp in c:\users\aviral verma\anaconda3\lib\site-packages (from datasets) (3.11.10)
Collecting huggingface-hub>=0.23.0 (from datasets)
  Using cached huggingface_hub-0.27.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\aviral verma\anaconda3\lib\site-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\aviral verma\anaconda3\lib\site-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\aviral verma\anaconda3\lib\site-packages (from aiohttp->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\aviral verma\anaconda3\lib\site-packages (from aiohttp->datasets) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\aviral verma\anaconda3\lib\site-packages (from aiohttp->datasets) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\aviral verma\anaconda3\lib\site-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\aviral verma\anaconda3\lib\site-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\aviral verma\anaconda3\lib\site-packages (from aiohttp->datasets) (0.2.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\aviral verma\anaconda3\lib\site-packages (from aiohttp->datasets) (1.18.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\aviral verma\anaconda3\lib\site-packages (from huggingface-hub>=0.23.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\aviral verma\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\aviral verma\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\aviral verma\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\aviral verma\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (2024.12.14)
Requirement already satisfied: colorama in c:\users\aviral verma\anaconda3\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aviral verma\anaconda3\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aviral verma\anaconda3\lib\site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aviral verma\anaconda3\lib\site-packages (from pandas->datasets) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\aviral verma\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Using cached datasets-3.2.0-py3-none-any.whl (480 kB)
Using cached huggingface_hub-0.27.0-py3-none-any.whl (450 kB)
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
Downloading xxhash-3.5.0-cp311-cp311-win_amd64.whl (30 kB)
Installing collected packages: xxhash, multiprocess, huggingface-hub, datasets
Successfully installed datasets-3.2.0 huggingface-hub-0.27.0 multiprocess-0.70.16 xxhash-3.5.0

In [2]:
from datasets import load_dataset

ds = load_dataset("wikimedia/wikipedia", "20231101.hi")

In [3]:
ds = ds['train'].to_pandas()

In [4]:
ds.shape

(163093, 4)

In [5]:
ds.drop_duplicates(inplace=True)

In [6]:
ds.shape

(163093, 4)

In [7]:
ds

,id,url,title,text
0,10,https://hi.wikipedia.org/wiki/%E0%A4%B9%E0%A4%...,हम होंगे कामयाब,हम होंगे कामयाब ( का गिरिजा कुमार माथुर द्वारा...
1,14,https://hi.wikipedia.org/wiki/%E0%A4%A6%E0%A5%...,दैनिक पूजा,दैनिक पूजा विधि हिन्दू धर्म की कई उपासना पद्धत...
2,54,https://hi.wikipedia.org/wiki/%E0%A4%B9%E0%A4%...,हिन्दी,हिन्दी जिसके मानकीकृत रूप को मानक हिन्दी कहा ज...
3,56,https://hi.wikipedia.org/wiki/%E0%A4%AB%E0%A4%...,फ़ारसी भाषा,"फ़ारसी (), एक भाषा है जो ईरान, ताजिकिस्तान, अफ..."
4,58,https://hi.wikipedia.org/wiki/%E0%A4%A6%E0%A5%...,देवनागरी,देवनागरी भारतीय उपमहाद्वीप में प्रयुक्त प्राची...
...,...,...,...,...
163088,1492984,https://hi.wikipedia.org/wiki/%E0%A4%9F%E0%A5%...,टोनांतिंस,() ब्राज़ील के आमेज़ोनास राज्य का शहर है। इसकी...
163089,1492985,https://hi.wikipedia.org/wiki/%E0%A4%AC%E0%A4%...,"बार्सेलोस, आमेज़ोनास",बार्सेलोस () ब्राज़ील के आमेज़ोनास राज्य का शह...
163090,1493004,https://hi.wikipedia.org/wiki/%E0%A4%A6%20%E0%...,द नन (2018 फिल्म),द नन 2018 की अमेरिकी गॉथिक अलौकिक हॉरर फिल्म ह...
163091,1493015,https://hi.wikipedia.org/wiki/%E0%A4%B6%E0%A4%...,शहज़ाद शेख,शहज़ाद शेख एक भारतीय टेलीविजन अभिनेता हैं। उन...
163092,1493018,https://hi.wikipedia.org/wiki/%E0%A4%86%E0%A4%...,आइरिस मैती,आइरिस मैती एक भारतीय मॉडल और अभिनेत्री हैं। उन...

In [8]:
ds.drop(['id', 'url'],axis=1, inplace=True)

In [9]:
ds

,title,text
0,हम होंगे कामयाब,हम होंगे कामयाब ( का गिरिजा कुमार माथुर द्वारा...
1,दैनिक पूजा,दैनिक पूजा विधि हिन्दू धर्म की कई उपासना पद्धत...
2,हिन्दी,हिन्दी जिसके मानकीकृत रूप को मानक हिन्दी कहा ज...
3,फ़ारसी भाषा,"फ़ारसी (), एक भाषा है जो ईरान, ताजिकिस्तान, अफ..."
4,देवनागरी,देवनागरी भारतीय उपमहाद्वीप में प्रयुक्त प्राची...
...,...,...
163088,टोनांतिंस,() ब्राज़ील के आमेज़ोनास राज्य का शहर है। इसकी...
163089,"बार्सेलोस, आमेज़ोनास",बार्सेलोस () ब्राज़ील के आमेज़ोनास राज्य का शह...
163090,द नन (2018 फिल्म),द नन 2018 की अमेरिकी गॉथिक अलौकिक हॉरर फिल्म ह...
163091,शहज़ाद शेख,शहज़ाद शेख एक भारतीय टेलीविजन अभिनेता हैं। उन...
163092,आइरिस मैती,आइरिस मैती एक भारतीय मॉडल और अभिनेत्री हैं। उन...

In [10]:
ds.drop_duplicates(inplace=True)

In [11]:
ds.shape

(163093, 2)

In [13]:
!pip install datasketch

Collecting datasketch
  Downloading datasketch-1.6.5-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: numpy>=1.11 in c:\users\aviral verma\anaconda3\lib\site-packages (from datasketch) (2.2.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\aviral verma\anaconda3\lib\site-packages (from datasketch) (1.13.1)
Downloading datasketch-1.6.5-py3-none-any.whl (89 kB)
Installing collected packages: datasketch
Successfully installed datasketch-1.6.5

In [14]:
from datasketch.minhash import MinHash

In [15]:
ds['title_text'] = ds['title'] + ds['text']

In [ ]:
# for OOM error, i have taken 16000 rows

In [20]:
shingles = ds['title_text'][:16000].to_numpy()

In [30]:
signatures = []
cnt = 0
for i_doc in range(len(shingles)):
    cnt = cnt + 1;
    if cnt%1000 == 0:
        print(cnt)
    m = MinHash()
    for d in shingles[i_doc]:
        m.update(d.encode('utf8'))
    signatures.append(m)

index_keep = []    
for i_doc in range(len(shingles)-1):
    flag = True
    for j_doc in range(i_doc + 1, len(shingles)):
        jaccard_similarity = signatures[i_doc].jaccard(signatures[j_doc])
        if jaccard_similarity > 0.75:
            flag = False
            break
    if flag:
        index_keep.append(i_doc)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000

In [31]:
len(jac_sim)

127992000

In [36]:
shingles[0]

'हम होंगे कामयाबहम होंगे कामयाब ( का गिरिजा कुमार माथुर द्वारा किया गया हिंदी भावानुवाद) एक प्रतिरोध गीत है। यह गीत बीसवीं सदी में नागरिक अधिकार आंदोलन का प्रधान स्वर बना। इस गीत को आमतौर पर "I\'ll Overcome Some Day" ("आई विल ओवरकम सम डे") से काव्यावतरित माना जाता है, जो चार्ल्स अल्बर्ट टिंडले द्वारा गाया गया था और जिसे 1900 में पहली बार प्रकाशित किया गया था।\n\nसन्दर्भ\nHum Honge Kamyab Lyrics \nनागरिक अधिकार आंदोलन\nदेशभक्ति के गीत\nआधार'

In [37]:
words = []
for i in index_keep:
    words.append(shingles[i])

In [39]:
words

['उत्तर दिशाउत्तर दिशा मुख्य चार दिशाओं में से एक है। \n\nदिशाएँ\n\nda:Kompasretning#Nord भारत उपमहाद्वीप के उत्तर में हिमालय है',
 'वायरस(1) कम्प्यूटर वायरस\n\n(2) जैविक वायरस या विषाणु',
 'मईमई ग्रेगोरी कैलेंडर के वर्ष का पांचवां महीना है जिसमे 31 दिन होते हैं।\n\nदिवस\n 1 मई - मई दिवस, मजदूर दिवस।\n 22 मई - विश्व जैव विविधता दिवस\n\n \n8 may:world redcross day',
 'हिरोडोटसहिरोडोटस (ग्रीक: Ἡρόδοτος Ἁλικαρνᾱσσεύς Hērodotos Halikarnāsseus) (मृत्\u200dयु ४२५ ई.पू), यूनान के इतिहासकार एवं भूगोलवेत्ता थे। उन्होंने अपने इतिहास का विषय पेलोपोनेसियन युद्ध को बनाया था। उनके द्वारा लिखित पुस्तक हिस्टोरिका थी।\n\nभूगोलवेत्ता\nयूनानी भूगोलवेत्ता',
 'अम्मानअम्मान (अरबी عمان), जोर्डन राज्य की राजधानी, १२ लाख से ज़्यादा लोगों का शहर है।\n\nबाहरी कडियाँ \n अल अह्लिय्या अम्मान विश्वविद्यालय जालस्थल - अंग्रेज़ी में अम्मान के बारे में जानकारी\n\nएशियाई शहर\nएशिया में राजधानियाँ',

In [40]:
import re
from collections import defaultdict

def get_stats(vocab):
    pairs = defaultdict(int)
    for word, freq in vocab.items():
        symbols = word.split()
        for i in range(len(symbols)-1):
            pairs[symbols[i],symbols[i+1]] += freq
    return pairs

def merge_vocab(pair, v_in):
    v_out = {}
    bigram = re.escape(' '.join(pair))
    p = re.compile(r'(?<!\S)' + bigram + r'(?!\S)')
    for word in v_in:
        w_out = p.sub(''.join(pair), word)
        v_out[w_out] = v_in[word]
    return v_out

def get_vocab(data):
    vocab = defaultdict(int)
    for line in data:
        for word in line.split():
            vocab[' '.join(list(word)) + ' </w>'] += 1
    return vocab

def byte_pair_encoding(data, n):
    vocab = get_vocab(data)
    for i in range(n):
        pairs = get_stats(vocab)
        best = max(pairs, key=pairs.get)
        vocab = merge_vocab(best, vocab)
    return vocab

# Example usage:
data = words

n = 230
bpe_pairs = byte_pair_encoding(data, n)
bpe_pairs

{'उत् त र</w>': 91,
 'दि शा उत् त र</w>': 1,
 'दि श ा</w>': 21,
 'मु ख ्य</w>': 93,
 'चा र</w>': 50,
 'दि शा ओं</w>': 1,
 'में</w>': 5163,
 'से</w>': 2714,
 'एक</w>': 1924,
 'है।</w>': 2364,
 'दि शा ए ँ</w>': 2,
 'd a : K o m p a s r e t n in g # N or d</w>': 1,
 'भार त</w>': 351,
 'उ प म हा द्व ी प</w>': 17,
 'के</w>': 8115,
 'हि मा ल य</w>': 13,
 'है</w>': 1358,
 'वा य र स ( 1 )</w>': 1,
 'क म् प ्य ू ट र</w>': 8,
 'वा य र स</w>': 5,
 '( 2 )</w>': 6,
 'ज ै वि क</w>': 6,
 'या</w>': 541,
 'वि ष ा ण ु</w>': 1,
 'म ई म ई</w>': 1,
 'ग ्रे ग ो री</w>': 20,
 'क ै ले ंड र</w>': 68,
 'वर् ष </w>': 184,
 'का</w>': 2795,
 'पा ं च वा ं</w>': 5,
 'म ह ी ना</w>': 5,
 'जि सम े</w>': 5,
 '3 1 </w>': 7,
 'दि न</w>': 197,
 'हो ते</w>': 110,
 'हैं।</w>': 868,
 'दि व स</w>': 19,
 '1 </w>': 53,
 'म ई</w>': 33,
 '-</w>': 449,
 'दि व स ,</w>': 1,
 'म ज द ू र</w>': 3,
 'दि व स ।</w>': 1,
 '2 2 </w>': 14,
 'वि श् व</w>': 127,
 'ज ै व</w>': 3,
 'वि वि ध ता</w>': 7,
 '8 </w>': 28,
 'm a y : w or l d</w>': 1,
 'r e d c r o s s</w>': 1,
 'd a y</w>': 2,
 'हि रो ड ो ट स हि रो ड ो ट स</w>': 1,
 '( ग ्र ी क :</w>': 1,
 'Ἡ ρ ό δ ο τ ο ς </w>': 1,
 'Ἁ λ ι κ α ρ ν ᾱ σ σ ε ύ ς </w>': 1,
 'H ē r o d o t o s</w>': 1,
 'H al i k ar n ā s s e u s )</w>': 1,
 '( म ृ त् \u200d य ु</w>': 1,
 '४ २ ५ </w>': 1,
 'ई . पू ) ,</w>': 1,
 'य ू ना न</w>': 11,
 'इ ति हा स कार</w>': 25,
 'ए व ं</w>': 278,
 'भ ू ग ो ल व े त् ता</w>': 15,
 'थे ।</w>': 344,
 'उन् हो ं ने</w>': 267,
 'अप ने</w>': 444,
 'इ ति हा स</w>': 129,
 'वि ष य</w>': 38,
 'प े लो प ो ने स िय न</w>': 1,
 'यु द् ध</w>': 109,
 'को</w>': 2216,
 'ब ना या</w>': 33,
 'था।</w>': 584,
 'उन के</w>': 259,
 'द्वारा</w>': 507,
 'लि ख ित</w>': 9,
 'पु स्त क</w>': 41,
 'हि स्ट ो रि का</w>': 1,
 'थ ी ।</w>': 179,
 'य ू ना नी</w>': 18,
 'अ म् मान अ म् मा न</w>': 1,
 '( अ र ब ी</w>': 14,
 'ع م ا ن ) ,</w>': 1,
 'ज ो र् ड न</w>': 1,
 'राज ्य</w>': 218,
 'की</w>': 3428,
 'राज धा नी ,</w>': 3,
 '१ २ </w>': 6,
 'ला ख </w>': 25,
 'ज़ ्या द ा</w>': 10,
 'लो ग ों</w>': 152,
 'श ह र</w>': 296,
 'बा ह री</w>': 166,
 'क ड िया ँ</w>': 6,
 'अ ल</w>': 33,
 'अ ह ् ल िय ्य ा</w>': 1,
 'अ म् मा न</w>': 2,
 'वि श् व वि द ्या ल य</w>': 64,
 'जा ल स् थ ल</w>': 18,
 'अ ंग ्रे ज़ ी</w>': 14,
 'ब ार े</w>': 116,
 'जा न कार ी</w>': 18,
 'ए श िया ई</w>': 7,
 'ए श िया</w>': 52,
 'राज धा न िया ँ</w>': 8,
 'द ी पा व ल ी द ी पा व ली</w>': 1,
 '( </w>': 56,
 '= </w>': 87,
 'द ी प</w>': 3,
 '+ </w>': 148,
 'आ व लि ः </w>': 1,
 'प ं क् ति ,</w>': 1,
 'अ र् था त् </w>': 9,
 'प ं क् ति</w>': 4,
 'र ख े</w>': 8,
 'हु ए</w>': 182,
 'द ी प क )</w>': 1,
 'श र द ृ त ु</w>': 1,
 '( उत् त री</w>': 1,
 'ग ो ला र् ध )</w>': 1,
 'प्र ति वर् ष </w>': 3,
 'म ना या</w>': 50,
 'जा ने</w>': 158,
 'वा ला</w>': 92,
 'प ौ रा ण िक</w>': 18,
 'स ना त न</w>': 5,
 'उत् स व</w>': 44,
 'यह</w>': 788,
 'का र् ति क</w>': 6,
 'मा स</w>': 18,
 'अ मा व स् या</w>': 4,
 'जाता</w>': 627,
 'और</w>': 3622,
 'स ब से</w>': 299,
 'ब ड़ े</w>': 68,
 'स र् वा ध िक</w>': 16,
 'म ह त् व पूर् ण</w>': 97,
 'त ्य ो ह ार ों</w>': 3,
 'आ ध ्या त् मि क</w>': 33,
 'रूप</w>': 783,
 "' अ न् ध कार</w>": 1,
 'पर</w>': 1060,
 'प्र का श</w>': 30,
 "वि ज य ' </w>": 1,
 'द र् शा ता</w>': 9,
 'भार त वर् ष </w>': 1,
 'म ना ए</w>': 2,
 'वा ले</w>': 164,
 'स भी</w>': 171,
 'प र् व ों</w>': 3,
 'द ी पा व ली</w>': 88,
 'सा मा जि क</w>': 40,
 'धा र् मि क</w>': 77,
 'द ो न ों</w>': 115,
 'द ृ ष् ट ि</w>': 21,
 'अ त ्य ध िक</w>': 17,
 'म ह त् त् व</w>': 15,
 'इ से</w>': 146,
 'द ी प ो त् स व</w>': 1,
 'भी</w>': 945,
 'क ह ते</w>': 106,
 '‘ त म स ो</w>': 1,
 'म ा</w>': 10,
 'ज ्य ो ति र् ग म य ’ </w>': 1,
 'अ र् था त</w>': 14,
 '( ह े</w>': 1,
 'भ ग वा न ! )</w>': 1,
 'मु झ े</w>': 10,
 'अ न् ध कार</w>': 3,
 'ओ र</w>': 56,
 'ले</w>': 51,
 'जा इ ए ।</w>': 1,
 'उ प नि ष द ों</w>': 5,
 'आ ज ् ञ ा</w>': 5,
 'सि ख ,</w>': 1,
 'ब ौ द् ध</w>': 13,
 'त था</w>': 237,
 'ज ै न</w>': 28,
 'ध र् म</w>': 117,
 'लो ग</w>': 218,
 'म ना ते</w>': 20,
 'म हा व ी र</w>': 5,
 'म ो क्ष </w>': 10,
 'है ं</w>': 445,
 'सि ख </w>': 11,
 'स मु दा य</w>': 58,
 'ब न् दी</w>': 2,
 'छ ो ड़ </w>': 30,
 'म ना ता</w>': 4,
 'मा ना</w>': 146,
 'कि</w>': 809,
 'अ यो ध ्य ा</w>': 9,
 'राज ा</w>': 75,
 'रा म</w>': 22,
 'च ौ द ह</w>': 5,
 'व न वा स</w>': 4,
 'प श् चा त</w>': 13,
 'ल ौ ट े</w>': 5,
 'अ यो ध ्या वा स ियों</w>': 2,
 'ह ृ द य</w>': 6,
 'प र म</w>': 10,
 'प्र िय </w>': 3,
 'आ ग म न</w>': 8,
 'प्र फ ु ल् लि त</w>': 1,
 'ह ो</w>': 393,
 'उ ठ ा</w>': 3,
 'श ्र ी</w>': 34,
 'स् वा ग त</w>': 9,
 'ने</w>': 1197,
 'घ ी</w>': 3,
 'द ी प क</w>': 7,
 'ज ला ए ।</w>': 2,
 'स घ न</w>': 1,
 'का ली</w>': 6,
 'व ह</w>': 258,
 'रा त्र ि</w>': 12,
 'द ी य ों</w>': 3,
 'रो श नी</w>': 3,
 'ज ग म ग ा</w>': 2,
 'उ ठ ी ।</w>': 1,
 'त ब</w>': 62,
 'आ ज</w>': 53,
 'त क</w>': 360,
 'भार त ीय</w>': 279,
 'प्र ति</w>': 61,
 'प्र का श - प र् व</w>': 1,
 'ह र् ष </w>': 5,
 'व</w>': 90,
 'उ ल् ला स</w>': 1,
 'भार त ी य ों</w>': 10,
 'वि श् वा स</w>': 57,
 'स त ्य</w>': 17,
 'स द ा</w>': 7,
 'जी त</w>': 31,
 'हो ती</w>': 161,
 'अ स त ्य</w>': 3,
 'ना श</w>': 2,
 'हो ता</w>': 300,
 'य ही</w>': 20,
 'च रि ता र् थ</w>': 1,
 'कर ती</w>': 85,
 'है -</w>': 23,
 'अ स त ो</w>': 1,
 'स द् ग म य ,</w>': 1,
 'त म स ो</w>': 2,
 'ज ्य ो ति र् ग म य ।</w>': 2,
 'स्व च ् छ ता</w>': 1,
 'प र् व</w>': 32,
 'क ई</w>': 285,
 'स प ् ता ह</w>': 40,
 'पूर् व</w>': 146,
 'ही</w>': 395,
 'त ै य ार िया ँ</w>': 2,
 'आ र ं भ </w>': 14,
 'जा ती</w>': 141,
 'घ रो ं,</w>': 3,
 'द ु का न ों</w>': 4,
 'आ द ि</w>': 62,
 'स फ ा ई</w>': 2,
 'का र् य</w>': 44,
 'कर</w>': 473,
 'दे ते</w>': 33,
 'घ र ों</w>': 15,
 'म र म्म त ,</w>': 1,
 'र ंग - रो ग न ,</w>': 1,
 'स फ े दी</w>': 1,
 'हो ने</w>': 166,
 'ल ग ता</w>': 16,
 'स्व च ् छ </w>': 15,
 'स जा ते</w>': 4,
 'बा ज ार ों</w>': 3,
 'ग ल ियों</w>': 3,
 'स् वर् ण ि म</w>': 1,
 'झ ंड ियों</w>': 1,
 'स जा या</w>': 9,
 'पह ले</w>': 251,
 'घ र - म ो ह ल् ले ,</w>': 1,
 'बा जा र</w>': 4,
 'स ब</w>': 27,
 'स ज े</w>': 1,
 'दि ख ते</w>': 2,
 'ने पा ल ,</w>': 1,
 'भार त ,</w>': 6,
 'श ्र ी ल ं का ,</w>': 3,
 'म ्या ं म ार ,</w>': 3,
 'म ार ी श स ,</w>': 1,
 'ग ु या ना ,</w>': 2,
 'त्र ि नि दा द</w>': 3,
 'ट ो ब ै ग ो ,</w>': 2,
 'स ू र ी ना म ,</w>': 2,
 'म ले श िया ,</w>': 6,
 'सि ंग ा पु र ,</w>': 5,
 'फ ि जी ,</w>': 2,
 'पा कि स् ता न</w>': 53,
 'औ स्ट ्रे ल िया</w>': 1,
 'स ी म ा</w>': 47,
 'क ्र ि सम स</w>': 10,
 'द्व ी प</w>': 84,
 'स र कार ी</w>': 9,
 'अ व का श</w>': 10,
 'श ब् द</w>': 171,
 'उत् प त् ति</w>': 25,
 'सं स् कृ त</w>': 46,
 'द ो</w>': 168,
 'श ब् द ों</w>': 36,
 "' द ी प ' </w>": 1,
 "' द िया ' </w>": 1,
 "' आ व ल ी ' </w>": 1,
 "' ला इ न ' </w>": 1,
 "' श ्र ृ ं ख ला ' </w>": 1,
 'मि श ्र ण</w>': 6,
 'हु ई</w>': 121,
 'कु छ </w>': 366,
 '" द ी पा व ल ी " </w>': 1,
 'त ो</w>': 193,
 '" दि पा व ल ी " </w>': 1,
 '; </w>': 29,
 'व ही</w>': 18,
 '" दि वा ल ी " </w>': 1,
 '" द ी वा ल ी " </w>': 1,
 'प्र यो ग</w>': 145,
 'कर ते</w>': 237,
 '।</w>': 80,
 'स् था नि क</w>': 1,
 'दि व ार ी</w>': 1,
 "' दि पा ल ी ' - ' द ी पा लि ' </w>": 1,
 'भ ी ।</w>': 5,
 'इस के</w>': 208,
 'द्व ार ो ं,</w>': 1,
 'म ं दि र ों</w>': 5,
 'ला ख ों</w>': 2,
 'प्र का श क ों</w>': 1,
 'प्र ज ् व लि त</w>': 1,
 'किया</w>': 678,
 'जि से</w>': 110,
 'दि वा ली</w>': 3,
 'उ से</w>': 103,
 'अन ्य</w>': 267,
 'भा ष ा ओं</w>': 59,
 'अ ल ग - अ ल ग</w>': 21,
 'ना म ों</w>': 24,
 'पु कार</w>': 2,
 'ज ै से</w>': 163,
 ':</w>': 103,
 "' द ी पा व ल ी ' </w>": 2,
 '( उ ड़ िया ) ,</w>': 1,
 "द ी पा ब ॉ ल ी ' ( ब ंग ा ल ी ) ,</w>": 1,
 '( अ सम ी ,</w>': 1,
 'क न् न ड़ ,</w>': 2,
 'म ल या ल म : ദ ീ പ ാ വ ല ി ,</w>': 1,
 'त मि ल : த ீ ப ா வ ள ி </w>': 1,
 'त े ल ु ग ू ) ,</w>': 1,
 "' दि वा ल ी ' </w>": 1,
 '( ग ु ज रा त ी : દ િ વ ા ળ ી ,</w>': 1,
 'हि न्द ी ,</w>': 5,
 'दि वा ल ी ,</w>': 1,
 'म रा ठ ी : दि वा ळ ी ,</w>': 1,
 'को ं क ण ी : दि वा ळ ी , प ं जा ब ी ) ,</w>': 1,
 "' द िय ार ी ' </w>": 1,
 '( सि ं ध ी : द िय ार ी \u200e ) ,</w>': 1,
 "' ति ह ार ' </w>": 1,
 '( ने पा ल ी )</w>': 1,
 'म ार वा ड़ ी</w>': 1,
 'द िया ळ ी ।</w>': 1,
 'प्रा च ीन</w>': 88,
 'का ल</w>': 94,
 'वि क ्र म</w>': 1,
 'सं व त</w>': 2,
 'मा ह</w>': 8,
 'ग र् म ी</w>': 8,
 'फ स ल</w>': 3,
 'बा द</w>': 438,
 'त ्य ो हा र</w>': 23,
 'द र् शा या</w>': 3,
 'ग या ।</w>': 165,
 'प द् म</w>': 10,
 'पु रा ण</w>': 14,
 'स् क न् द</w>': 2,
 'उ ल् ले ख </w>': 24,
 'मि ल ता</w>': 31,
 'य े</w>': 185,
 'ग ्र न् थ</w>': 24,
 'पह ली</w>': 80,
 'स ह स् त्र ा ब् दी</w>': 2,
 'द ू स र े</w>': 67,
 'भा ग</w>': 108,
 'कि न् ह ीं</w>': 1,
 'के ं द ्र ीय</w>': 15,
 'पा ठ </w>': 24,
 'वि स्त ृ त</w>': 15,
 'लि ख े</w>': 13,
 'ग ए</w>': 147,
 'द ी य े</w>': 3,
 '( द ी प क )</w>': 1,
 'स ू र् य</w>': 14,
 'हि स् स ों</w>': 8,
 'प्र ति नि ध ि त् व</w>': 11,
 'करने</w>': 535,
 'गया</w>': 567,
 'है,</w>': 582,
 'जो</w>': 643,
 'जी व न</w>': 122,
 'लिए</w>': 933,
 'ऊ र् ज ा</w>': 51,
 'ल ौ कि क</w>': 4,
 'दा ता</w>': 1,
 'हि न्द ू</w>': 52,
 'क ै ल ंड र</w>': 10,
 'अनु सा र</w>': 121,
 'अप नी</w>': 204,
 'स् ति थ ि</w>': 1,
 'ब द ल ता</w>': 4,
 'क्ष े त्र ों</w>': 51,
 'य म</w>': 3,
 'न च ि के ता</w>': 2,
 'क था</w>': 13,
 'साथ</w>': 473,
 'ज ो ड़ ते</w>': 4,
 'स ही</w>': 24,
 'ब ना म</w>': 4,
 'ग ल त ,</w>': 1,
 'ज ् ञ ा न</w>': 46,
 'अ ज ् ञ ा न ,</w>': 2,
 'स च ् च ा</w>': 1,
 'ध न</w>': 30,
 'क्ष ण िक</w>': 1,
 'ब ता ती</w>': 12,
 'है ; </w>': 46,
 'ई स ा</w>': 48,
 'उ प नि ष द</w>': 3,
 'दि पा व ली</w>': 8,
 'रा मा य ण</w>': 8,
 'ज ु ड़ ा</w>': 14,
 'हु आ </w>': 161,
 'ऐ स ा</w>': 60,
 'च न् द् र</w>': 19,
 'ज ी</w>': 41,
 'मा ता</w>': 20,
 'स ी ता</w>': 4,
 'रा व ण</w>': 5,
 'क ै द</w>': 6,
 'छ ु ड़ ा या</w>': 1,
 'उन की</w>': 156,
 'अ ग ् न ि</w>': 5,
 'प र ी क्ष ा</w>': 2,
 'उ प रा न् त ,</w>': 1,
 '1 4 </w>': 47,
 'व ्य त ी त</w>': 1,
 'वा प स</w>': 39,
 'लो ट े</w>': 1,
 'वा स ियों</w>': 1,
 'जी ,</w>': 2,
 'स ी ता ,</w>': 1,
 'अनु ज</w>': 2,
 'ल क्ष म ण</w>': 1,
 'ह े त ु</w>': 22,
 'स म् पूर् ण</w>': 20,
 'ज ला कर</w>': 4,
 'रो श न</w>': 3,
 'था ,</w>': 196,
 'त भी</w>': 5,
 'द ी प ों</w>': 2,
 'त ्य ौ हा र</w>': 29,
 'ले कि न</w>': 227,
 'आ प को</w>': 10,
 'जा न कर</w>': 3,
 'ब हु त</w>': 168,
 'है रा नी</w>': 1,
 'हो ग ी</w>': 3,
 'के व ल</w>': 94,
 '2 </w>': 33,
 'म ना य ी</w>': 2,
 'ग ई</w>': 91,
 '७ व ीं</w>': 3,
 'श ता ब् दी</w>': 108,
 'ना ट क</w>': 10,
 'ना ग न ं द</w>': 1,
 'द ी प प्र ति पा द ु त् स व ः </w>': 1,
 'क ह ा</w>': 214,
 'जि स में</w>': 120,
 'ज ला य े</w>': 1,
 'जा ते</w>': 106,
 'थ े</w>': 110,
 'न व</w>': 14,
 'व र - ब ध ू</w>': 1,
 'उ प हा र</w>': 11,
 'दि ए</w>': 31,
 '9 </w>': 50,
 'व ीं</w>': 56,
 'राज श े ख र</w>': 1,
 'का व ्य म ी मा ं स ा</w>': 1,
 'द ी प मा लि का</w>': 1,
 'पु ता ई</w>': 1,
 'थ ी</w>': 73,
 'त े ल</w>': 29,
 'रा त</w>': 22,
 'स ड़ क ों</w>': 8,
 'फ ार सी</w>': 18,
 'या त्र ी</w>': 10,
 'ब े र ु नी ,</w>': 1,
 '१ १ </w>': 4,
 'स दी</w>': 64,
 'सं स् म र ण</w>': 2,
 'मे ं,</w>': 306,
 'म ह ी ने</w>': 26,
 'न य े</w>': 11,
 'च ं द ्र म ा</w>': 6,
 'हि ं द ु ओं</w>': 7,
 'ने पा ल</w>': 39,
 'सु ख द</w>': 1,
 'छ ु ट ् ट ियों</w>': 8,
 'सा फ </w>': 11,
 'उन् ह ें</w>': 208,
 'ने पा ल ियों</w>': 1,
 'इस लिए</w>': 47,
 'म हा न</w>': 63,
 'क ्य ो ं कि</w>': 103,
 'इस</w>': 756,
 'न या</w>': 12,
 'श ु रू </w>': 121,
 'श ॉ प ि ं ग</w>': 1,
 'स ी ज न</w>': 2,
 'द ौ रा न</w>': 146,
 'कार ें</w>': 1,
 'स ो ने</w>': 8,
 'ग ह ने</w>': 4,
 'म ह ंग ी</w>': 3,
 'व स्त ु ए ँ</w>': 6,
 'स्व य ं</w>': 37,
 'परि व ार ों</w>': 6,
 'क प ड़ े ,</w>': 3,
 'उ पह ार ,</w>': 2,
 'उ प कर ण ,</w>': 1,
 'र स ो ई</w>': 3,
 'ब र् त न</w>': 3,
 'ख र ी द ते</w>': 1,
 'परि वा र</w>': 81,
 'स द स् य ों</w>': 15,
 'द ो स्त ों</w>': 7,
 'स्व र ु प</w>': 6,
 'आ म</w>': 47,
 'त ौ र</w>': 53,
 'मि ठ ा इ या ँ</w>': 3,
 'स ू ख े</w>': 3,
 'मे व े</w>': 1,
 'ब च ् च े</w>': 15,
 'मा ता - प ि ता</w>': 6,
 'ब ड़ ों</w>': 3,
 'अ च ् छ ा ई</w>': 3,
 'ब ु रा ई</w>': 6,
 'अ ं ध े र े</w>': 1,
 'ब ी च</w>': 181,
 'ल ड़ ा ई</w>': 47,
 'क हा न िय ो ं,</w>': 1,
 'क था ओ ं,</w>': 2,
 'मि थ क ों</w>': 3,
 'सु न ते</w>': 1,
 'ल ड़ क िया ँ</w>': 1,
 'म हि ला ए ँ</w>': 3,
 'ख र ी द ार ी</w>': 3,
 'फ र् श ,</w>': 1,
 'द र वा ज े</w>': 3,
 'पा स</w>': 60,
 'रा स्त ों</w>': 1,
 'र ंग ो ली</w>': 2,
 'र च ना त् म क</w>': 2,
 'प ै ट र् न</w>': 3,
 'ब ना ती</w>': 9,
 'यु व ा</w>': 21,
 'व य स् क</w>': 3,
 'आ ति श बा ज ी</w>': 15,
 'व ्य व स् था</w>': 26,
 'स हा य ता</w>': 24,
 'क्ष े त्र ीय</w>': 14,
 'आ धा र</w>': 70,
 'प्र था ओं</w>': 14,
 'र ी ति - रि वा ज ों</w>': 4,
 'ब द ला व</w>': 8,
 'पा या</w>': 34,
 'सम ृ द् ध ि</w>': 8,
 'दे व ी</w>': 66,
 'ल क्ष ् म ी</w>': 24,
 'अ ध िक</w>': 152,
 'दे व ता ओं</w>': 15,
 'पू ज ा</w>': 63,
 'को ,</w>': 11,
 'आ स मा न</w>': 1,
 'दे ती</w>': 15,
 'स द स् य</w>': 33,
 'आ म ं त्र ित</w>': 12,
 'मि त्र ग ण</w>': 1,
 'भ ो ज न</w>': 32,
 'मि ठ ा य ों</w>': 1,
 'वि भ ि न् न</w>': 72,
 'ऐ ति हा सि क</w>': 45,
 'घ ट ना ओ ं,</w>': 2,
 'क हा न ियों</w>': 17,
 'च ि ह ् नि त</w>': 6,
 'हि ं द ू ,</w>': 3,
 'सि ख ों</w>': 2,
 'व े</w>': 165,
 'अ च ् छ ा ई ,</w>': 2,
 'अ ं ध कार</w>': 5,
 'प्र का श ,</w>': 4,
 'अ ज ् ञ ा न</w>': 5,
 'नि रा श ा</w>': 1,
 'आ श ा</w>': 12,
 'वि ज य</w>': 34,
 'द र् शा ते</w>': 1,
 'हि न्द ु ओं</w>': 4,
 'यो ग ,</w>': 1,
 'व े दा न् त ,</w>': 1,
 'सा ं ख ्य</w>': 16,
 'द र् श न</w>': 58,
 'भ ौ ति क</w>': 31,
 'श र ी र</w>': 36,
 'म न</w>': 18,
 'प र े</w>': 9,
 'व हा ं</w>': 12,
 'श ु द् ध ,</w>': 1,
 'अन न् त ,</w>': 1,
 'शा श् व त</w>': 7,
 'आ त् म न् </w>': 8,
 'आ त् म ा</w>': 32,
 'द ी पा व ल ी ,</w>': 3,
 'आ न् त रि क</w>': 4,
 'ज ् ञ ा न ,</w>': 7,
 'हि ं द ू</w>': 21,
 'म ह त् व</w>': 22,
 'द र् श न ,</w>': 7,
 'मि थ को ं,</w>': 1,
 'कि ं व द ं त िय ो ं,</w>': 1,
 'मान ्य ता ओं</w>': 9,
 'नि र् भ र</w>': 12,
 'कर ता</w>': 159,
 'ब ता या</w>': 36,
 'कि ,</w>': 9,
 'सा ल</w>': 100,
 'भ ग वा न</w>': 50,
 'प त् नी</w>': 32,
 'भा ई</w>': 36,
 'ल क्ष ् म ण</w>': 1,
 'वा प सी</w>': 7,
 'स म् मा न</w>': 33,
 'मान ते</w>': 58,
 'म हा का व ्य</w>': 2,
 'म हा भार त</w>': 9,
 '1 2 </w>': 21,
 'वर् ष ों</w>': 44,
 'अ ज ् ञ ा त वा स</w>': 1,
 'पा ंड व ों</w>': 1,
 'प्र त ी क</w>': 27,
 'हि ं द ु</w>': 1,
 'वि ष् ण ु</w>': 22,
 'उत् स व ,</w>': 4,
 'पा ं च</w>': 21,
 'दि व स ीय</w>': 7,
 'म हो त् स व</w>': 5,
 'रा क्ष स ों</w>': 2,
 'द ू ध</w>': 12,
 'सा ग र</w>': 55,
 'म ं थ न</w>': 1,
 'प ै द ा</w>': 38,
 'ज न् म</w>': 107,
 'ज ब</w>': 180,
 'प ति</w>': 7,
 'च ु ना</w>': 15,
 'फ ि र</w>': 103,
 'उन से</w>': 16,
 'शा दी</w>': 24,
 'क ी ।</w>': 97,
 'सा थ - साथ</w>': 27,
 'भ क् त</w>': 7,
 'बा धा ओं</w>': 3,
 'द ू र</w>': 39,
 'ग ण े श ; </w>': 1,
 'सं ग ी त ,</w>': 6,
 'सा हि त ्य</w>': 65,
 'स र स्व त ी ; </w>': 1,
 'प्र ब ं ध क</w>': 2,
 'कु ब े र</w>': 5,
 'प्र सा द</w>': 9,
 'अ र् प ित</w>': 2,
 'व ै कु ण ् ठ </w>': 2,
 'मान ्य ता</w>': 28,
 'प्र स न् न</w>': 4,
 'र ह ती</w>': 19,
 'उ स</w>': 103,
 'आ ग े</w>': 52,
 'मान सि क ,</w>': 1,
 'श ार ी रि क</w>': 20,
 'द ु ख ों</w>': 1,
 'सु ख ी</w>': 4,
 'र ह ते</w>': 42,
 'पूर् व ी</w>': 71,
 'क्ष े त्र</w>': 175,
 'उ ड़ ी स ा</w>': 4,
 'प श् च ि म</w>': 66,
 'ब ंग ा ल</w>': 48,
 'ज ग ह</w>': 26,
 'हैं ,</w>': 204,
 'म थ ु र ा</w>': 1,
 'म ध ्य</w>': 66,
 'कृ ष् ण</w>': 15,
 'ग ो वर् ध न</w>': 2,
 '( या</w>': 14,
 'अ न् न क ू ट )</w>': 1,
 'दा व त</w>': 5,
 '5 6 </w>': 2,
 '1 0 8 </w>': 3,
 'व ्य ं ज न ों</w>': 9,
 'भ ो ग</w>': 1,
 'ल गा या</w>': 28,
 'सा ं झ े</w>': 1,
 'स् था न ीय</w>': 43,
 'उत् त री</w>': 47,
 'भा ग ों</w>': 15,
 'श ु र ु आ त</w>': 54,
 'ज ला ने</w>': 1,
 'प्र था</w>': 15,
 'प ी छ े</w>': 21,
 'कार ण</w>': 137,
 'क हा न िया ँ</w>': 5,
 'भ क् त ों</w>': 6,
 'ल ं का</w>': 4,
 'अ त ्या च ार ी</w>': 2,
 'व ध</w>': 6,
 'कर के</w>': 35,
 'ल ौ ट ने</w>': 11,
 'ख ु श ी</w>': 3,
 'भ क् ति ध ारा</w>': 1,
 'म त</w>': 21,
 'न र का सु र</w>': 7,
 'न ृ श ं स</w>': 1,
 'रा क्ष स</w>': 4,
 'ज न ता</w>': 21,
 'अ पा र</w>': 1,
 'फ ै ल</w>': 10,
 'प्र स न् न ता</w>': 4,
 'भ र े</w>': 4,
 'द ी ए</w>': 1,
 'वि ं ष् ण ु</w>': 1,
 'न र सि ं ह</w>': 3,
 'ध ार ण कर</w>': 1,
 'हि र ण ्य क श ्य प</w>': 1,
 'था</w>': 286,
 'इस ी</w>': 79,
 'स मु द ्र म ं थ न</w>': 1,
 'ध न् व ं तर ि</w>': 1,
 'प्र क ट</w>': 30,
 'हु ए ।</w>': 21,
 'म ता व ल ं ब ियों</w>': 1,
 'च ौ ब ी स व ें</w>': 1,
 'त ी र् थ ं कर ,</w>': 1,
 'स् वा म ी</w>': 14,
 'प्रा प ् ति</w>': 6,
 'प्र थ म</w>': 46,
 'श ि ष ्य ,</w>': 1,
 'ग ौ त म</w>': 12,
 'ग ण ध र</w>': 3,
 'प्रा प ् त</w>': 108,
 'स मा ज</w>': 42,
 'नि र् वा ण</w>': 2,
 'म ना ई</w>': 3,
 '( वर् त मा न</w>': 3,
 'अ व स र् प ि ण ी</w>': 1,
 'अ ं ति म</w>': 47,
 'त ी र् थ ं कर )</w>': 1,
 '( का र् ति क</w>': 1,
 'अ मा व स् या )</w>': 1,
 'सं ध ्या का ल</w>': 1,
 'श ि ष ्य</w>': 14,
 'अ त ः </w>': 15,
 'स म् प्र दा य ों</w>': 4,
 'पू ज न</w>': 5,
 'वि ध ि</w>': 18,
 'पूर् ण त ः </w>': 4,
 'भ ि न् न</w>': 21,
 'सि क् ख ों</w>': 2,
 'म ह त् त् व पूर् ण</w>': 12,
 'अ म ृ त स र</w>': 2,
 '1 5 7 7 </w>': 1,
 'स् वर् ण</w>': 8,
 'म न् दि र</w>': 16,
 'श ि ला न ्या स</w>': 1,
 'अ ला व ा</w>': 52,
 '1 6 19 </w>': 1,
 'छ ठ े</w>': 5,
 'ग ु र ु</w>': 9,
 'ह र ग ो ब ि न् द</w>': 1,
 'सि ं ह</w>': 26,
 'ज े ल</w>': 7,
 'रि ह ा</w>': 1,
 'प ं जा ब</w>': 18,
 'ज न् म े</w>': 68,
 'रा म त ी र् थ</w>': 1,
 'म हा प्र या ण</w>': 1,
 'हु आ ।</w>': 80,
 'इ न् हो ं ने</w>': 25,
 'ग ंग ा त ट</w>': 1,
 'स् ना न</w>': 3,
 'सम य</w>': 230,
 "' ओ म ' </w>": 1,
 'स मा ध ि</w>': 4,
 'ल ी ।</w>': 14,
 'म ह र् ष ि</w>': 4,
 'द या न न् द</w>': 1,
 'सं स् कृ ति</w>': 202,
 'ज न ना य क</w>': 1,
 'ब न कर</w>': 5,
 'अ ज मे र</w>': 1,
 'नि क ट</w>': 17,
 'अ व सा न</w>': 1,
 'ल िया ।</w>': 43,
 'आ र् य</w>': 4,
 'स् था प ना</w>': 76,
 'द ी न - ए - इ ला ही</w>': 1,
 'प्र वर् त क</w>': 5,
 'मु ग ल</w>': 18,
 'सम ्रा ट</w>': 28,
 'अ क ब र</w>': 11,
 'शा स न का ल</w>': 16,
 'द ौ ल त ख ा ने</w>': 1,
 'सा म ने</w>': 22,
 '4 0</w>': 10,
 'ग ज</w>': 1,
 'ऊ ँ च े</w>': 1,
 'बा ँ स</w>': 1,
 'ब ड़ ा</w>': 83,
 'आ का श द ी प</w>': 1,
 'ल ट का या</w>': 2,
 'बा द शा ह</w>': 3,
 'ज हा ँ ग ी र</w>': 5,
 'ध ू म धा म</w>': 1,
 'व ं श</w>': 73,
 'ब हा द ु र</w>': 7,
 'शा ह</w>': 42,
 'ज फ र</w>': 2,
 'अ व स र</w>': 17,
 'आ यो ज ित</w>': 23,
 'का र् य क ्र म ों</w>': 6,
 'ले ते</w>': 29,
 'आ ल म</w>': 3,
 'द् वि त ीय</w>': 34,
 'सम ू च े</w>': 1,
 'शा ही</w>': 16,
 'म ह ल</w>': 6,
 'ला ल कि ले</w>': 1,
 'हि न्द ू - मु स ल मा न</w>': 1,
 'आ र् थ िक</w>': 20,
 'प्र मु ख </w>': 226,
 'अ व ध ि</w>': 26,
 'उ प भ ो क् ता</w>': 3,
 'ख र ी द</w>': 3,
 'ग ति वि ध ियों</w>': 16,
 'सं द र् भ </w>': 26,
 'ब रा ब र</w>': 21,
 'न ए</w>': 44,
 'घ र</w>': 50,
 'सा मान ,</w>': 1,
 'ब ड़ ी</w>': 41,
 'ख ़ र ी द द ार ी</w>': 1,
 'ख र् च</w>': 5,
 'ख ़ र ी द</w>': 3,
 'श ु भ </w>': 10,
 'ध न ,</w>': 1,
 'सम ृ द् ध ि ,</w>': 1,
 'नि व े श</w>': 10,
 'द ी वा ली</w>': 2,
 'स ी ज़ न</w>': 23,
 'मि ठ ा ई ,</w>': 1,
 "' क ै ंड ी ' </w>": 1,
 'च र म</w>': 9,
 'प्र त ्य े क</w>': 30,
 'ह ज़ ा र</w>': 4,
 'कर ो ड़ </w>': 15,
 'र ु प ए</w>': 4,
 'प ट ा ख ों</w>': 3,
 'ख प त</w>': 3,
 'सं सा र</w>': 18,
 'वि श े ष </w>': 86,
 'द ु न िया</w>': 82,
 'भ र</w>': 34,
 'य े ,</w>': 2,
 'पा कि स् ता न ,</w>': 4,
 'था ई ल ै ंड ,</w>': 4,
 'इ ंड ो ने श िया ,</w>': 2,
 'ऑ स्ट ्रे ल िया ,</w>': 7,
 'न ्य ू जी ल ै ंड ,</w>': 3,
 'म ॉ र ी श स ,</w>': 1,
 'के न ्या ,</w>': 1,
 'त ं जा न िया ,</w>': 1,
 'द क्ष ि ण</w>': 151,
 'अ फ ्र ी का ,</w>': 2,
 'नी द र ल ै ंड ,</w>': 3,
 'क ना ड ा ,</w>': 1,
 'ब ्र ि ट े न</w>': 27,
 'शा मि ल</w>': 169,
 'सं यु क् त</w>': 93,
 'अ र ब</w>': 124,
 'अ म ी रा त ,</w>': 1,
 'अ मे रि का ।</w>': 1,
 'सम झ </w>': 9,
 'म ू ल</w>': 83,
 'व ै श् वि क</w>': 7,
 'प्र वा स</w>': 9,
 'म ना ने</w>': 12,
 'दे श ों</w>': 71,
 'सं ख ्य ा</w>': 41,
 'ध ी र े - ध ी र े</w>': 11,
 'ब ढ ़ </w>': 12,
 'र ही</w>': 45,
 'प्र वा स ियों</w>': 9,
 'स् था न ों</w>': 19,
 'सा मान ्य</w>': 48,
 'हि स् स ा</w>': 64,
 'ब न ता</w>': 15,
 'ज ा</w>': 161,
 'र ह ा</w>': 116,
 'इ न</w>': 140,
 'अ ध ि का ं श त ः </w>': 2,
 'मा म ू ली</w>': 8,
 'ले ख </w>': 21,
 'वर् ण ित</w>': 12,
 'उ सी</w>': 39,
 'त र् ज</w>': 1,
 'वि वि ध ता ए ँ</w>': 1,
 'ला य क</w>': 2,
 '" ति ह ार " </w>': 1,
 '" स्व न् ति " </w>': 1,
 'जा ना</w>': 115,
 'प र न् त ु</w>': 6,
 'प र म् प रा ओं</w>': 7,
 'भ ि न् न ता</w>': 7,
 'पा य ी</w>': 4,
 "' का ग</w>": 1,
 "ति ह ार ' </w>": 4,
 'प र ,</w>': 31,
 'क ौ ए</w>': 1,
 'प र मा त् म ा</w>': 4,
 'द ू त</w>': 7,